### PR TITLE
Modify DocIO GitHub and UG for document processing playground

### PR DESCRIPTION
**Pull request by Yaminisrisf4389**
Hi All,

Modify DocIO GitHub examples repository for document processing playground for below samples.
Extract-ole-object

### CODE REVIEW

**Review by LokeshBaskar — CHANGES_REQUESTED** [review]
Please revert the unwanted changes.

**Comment by Yaminisrisf4389** [comment]
Addressed the feedback

**Comment by Yaminisrisf4389** [comment]
> Please revert the unwanted changes.

feedback addressed

**Review by Ramaraj-Marimuthu — APPROVED** [review]
No concerns

**Pull request merged**
